from django.urls import path
from .views import authentification, user, administrator


urlpatterns = [
    path('auth/signin', authentification.signin_view),
    path('auth/login', authentification.login_view),
    path('auth/logout', authentification.logout_view),
    path('user/timetable/follow', user.get_timetable_follow_by_me_view),
    path('user/timetable/<int:timetable_pk>/follow', user.follow_timetable_view),
    path('user/timetable/<int:timetable_pk>/unfollow', user.unfollow_timetable_view),
    path('user/timetable', user.get_timetable_view),
    path('user/status/choice', user.get_status_choice_view),
    path('user/timetable/<int:timetable_pk>/classe', user.get_timetable_classes_view),
    path('user/timetable/<int:timetable_pk>/classe/<int:next_day>', user.get_timetable_classes_view),
    path('user/timetable/<int:timetable_pk>/lecturer', user.get_timetable_lecturer_view),
    path('user/timetable/<int:timetable_pk>/location', user.get_timetable_location_view),
    path('user/timetable/<int:timetable_pk>/course', user.get_timetable_course_view),
    path('user/timetable/<int:timetable_pk>/category', user.get_timetable_category_view),
    path('user/timetable/<int:timetable_pk>/event', user.get_timetable_event_view),
    path('user/timetable/<int:timetable_pk>/event/<int:next_day>', user.get_timetable_event_view),
    path('user/timetable/<int:timetable_pk>/asset', user.get_timetable_asset_view),
    path('user/timetable/asset/<asset_pk>/read', user.set_asset_reader_view),
    path('admin/timetable/add', administrator.add_timetable_view),
    path('admin/timetable/<int:timetable_pk>/delete', administrator.delete_timetable_view),
    path('admin/media/add', administrator.add_media_view),
    path('admin/timetable/course/<int:course_pk>/classe/add', administrator.add_timetable_classe_view),
    path('admin/timetable/classe/<int:classe_pk>/delete', administrator.delete_timetable_classe_view),
    path('admin/timetable/classe/<int:classe_pk>/update', administrator.update_timetable_classe_view),
    path('admin/timetable/course/<int:course_pk>/asset/add', administrator.add_course_asset_view),
    path('admin/timetable/asset/<int:asset_pk>/delete', administrator.delete_course_asset_view),
    path('admin/timetable/asset/<int:asset_pk>/update', administrator.update_course_asset_view),
    path('admin/timetable/course/add', administrator.add_timetable_course_view),
    path('admin/timetable/<int:timetable_pk>/lecturer/add', administrator.add_timetable_lecturer_view),
    path('admin/timetable/<int:timetable_pk>/location/add', administrator.add_timetable_location_view),
    path('admin/timetable/<int:timetable_pk>/category/add', administrator.add_timetable_category_view),
    path('admin/timetable/event/add', administrator.add_timetable_event_view),
    path('admin/timetable/event/<int:event_pk>/delete', administrator.delete_timetable_event_view),
    path('admin/timetable/event/<int:event_pk>/update', administrator.update_timetable_event_view),
]
